default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: IOT_development

test:
  <<: *default
  database: IOT_test

production:
  <<: *default
  database: IOT_production
